name: Workflow for push on coq-master branch of Trakt

on:
  push:
    branches:
      - coq-master
  pull_request:
    branches:
      - coq-master

jobs:
  master:
    strategy:
      matrix:
        coq-version: [dev]
    uses: ./.github/workflows/from-sources.yml
    with:
      coq-version: ${{ matrix.coq-version }}