name: Workflow for push on elpi-2 branch of Trakt

on:
  push:
    branches:
      - elpi-2
  pull_request:
    branches:
      - elpi-2

jobs:
  master:
    strategy:
      matrix:
        coq-version:
          - coqorg/coq:8.17
          - coqorg/coq:8.18
          - coqorg/coq:8.19
          - coqorg/coq:8.20
          - rocq/rocq-prover:9.0
    uses: ./.github/workflows/from-sources.yml
    with:
      coq-version: ${{ matrix.coq-version }}
